<x-mail::message>
<div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 24px; font-size: 14px; text-align: center; border: 1px solid #e2e8f0; color: #334155;">
    <strong>Garikothay.com Logo</strong>
</div>

@if(isset($purpose))
<div style="font-size: 18px; font-weight: 700; margin-bottom: 24px; text-align: center; color: #0f172a;">
    {{ $purpose }}
</div>
@endif

@if(isset($greeting))
<div style="margin-bottom: 20px; font-size: 16px; color: #334155;">
    {{ $greeting }}
</div>
@endif

<div style="color: #334155; font-size: 16px; line-height: 1.6;">
{{ $slot }}
</div>

@if(isset($reference))
<div style="background-color: #f1f5f9; padding: 16px; border-radius: 8px; margin-top: 32px; font-size: 14px; color: #475569; line-height: 1.6;">
    {!! nl2br(e(trim($reference))) !!}
</div>
@endif

@if(isset($cta))
<div style="text-align: center; margin-top: 32px; margin-bottom: 32px;">
    {{ $cta }}
</div>
@endif

@if(isset($actionRequired))
<div style="margin-top: 24px; font-size: 15px; font-weight: 600; color: #e11d48;">
    {{ $actionRequired }}
</div>
@endif

@if(isset($important))
<div style="background-color: #fef2f2; border: 1px solid #fca5a5; padding: 16px; border-radius: 8px; margin-top: 24px; font-size: 14px; color: #991b1b; line-height: 1.6;">
    <strong style="color: #7f1d1d;">Important</strong><br>
    {{ $important }}
</div>
@endif

<hr style="border: none; border-top: 1px solid #e2e8f0; margin: 32px 0;">

<div style="font-size: 13px; color: #64748b; margin-top: 24px; line-height: 1.5;">
    <strong style="color: #334155;">🔐 Security Notice</strong><br>
    Never share administrator passwords, OTPs, PINs, API credentials, or other sensitive security information.<br>
    Garikothay will never request administrator credentials through email, phone, or messaging platforms.<br>
    Always verify that you are accessing the official Garikothay.com Admin Panel before entering any credentials.
</div>

<div style="font-size: 13px; color: #64748b; margin-top: 24px; line-height: 1.5;">
    <strong style="color: #334155;">System Notice</strong><br>
    This is an automated administrative notification generated by the Garikothay Shop system.<br>
    This email is intended solely for authorized Garikothay personnel and may contain confidential operational information.<br>
    Do not forward or share this email with unauthorized individuals.
</div>

<div style="font-size: 14px; font-weight: 600; color: #334155; margin-top: 32px; text-align: center;">
    Every Journey Deserves Trust.
</div>
<div style="font-size: 13px; color: #64748b; text-align: center; margin-top: 8px;">
    Thank you for managing Garikothay.com.<br>
    — Team Garikothay.com<br><br>
    Garikothay.com<br>
    Dhaka, Bangladesh<br>
    © {{ date('Y') }} Garikothay.com. All Rights Reserved.
</div>
</x-mail::message>
